language: php
php:
  - 5.4
before_script:
  - mkdir -p build/logs
install:
  - composer install
  - composer require satooshi/php-coveralls:~0.6@stable
script:
  - phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml
after_success:
  - php vendor/bin/coveralls -v